// Code generated by awg. DO NOT EDIT.
package example

import (
	"context"
	"encoding/json"
	"math/rand"
)

// GetByIdAsync generated async wrapper for GetById function
func (s *Service) GetByIdAsync(ctx context.Context, number []*json.Number, str []string, n *int, q map[string]*rand.Rand, cl Closer, i interface{}) func() ([]*Object, error) {
	var (
		done = make(chan struct{})

		p0 []*Object
		p1 error
	)
	go func() {
		defer close(done)
		p0, p1 = s.GetById(ctx, number, str, n, q, cl, i)
	}()
	return func() ([]*Object, error) {
		<-done
		return p0, p1
	}
}
